version: 2
jobs:
  build:
    working_directory: ~/ci
    machine: true
    environment:
      USE_CCACHE: 1
      ANDROID_JACK_VM_ARGS: "-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx6G"
      WITH_SU: true
      ALLOW_MISSING_DEPENDENCIES: true
    steps:
      - checkout
      - restore_cache:
          key: cm-14.1-201908
      - run:
          name: Prepare
          command: ./.circleci/prepare.sh
      - run:
          name: Run build
          command: ./build.sh
          no_output_timeout: 60m
      - run:
          name: Deploy
          command: ./deploy.sh
      - save_cache:
          key: lineage-15.1-201908
          paths:
            - ~/.ccache
      - store_artifacts:
          path: release
          destination: out
